# Linguagem Utilizada para Desenvolver a Aplicação
language: python
dist: xenial
os: linux

# Versão que a aplicação suporta.
python:
  - "3.7.9"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask
 
# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test || travis_terminate 1;

# Definir o Deploy no GAE
deploy:
        provider: gae
        keyfile: /vagrant/mystical-magnet-315402-8f518299c260.json
        project: mystical-magnet-315402
        on:
                branch: main

before_install:
        - openssl aes-256-cbc -K $encrypted_1a144e751318_key -iv $encrypted_1a144e751318_iv
          - in mystical-magnet-315402-8f518299c260.json.enc -out ../mystical-magnet-315402-8f518299c260.json
          - d

